foundriesio/ci-scripts

- lmp/jobserv.yml
> lmp/jobserv: add build jobs for apalis-imx6

- lmp/host_tests.py
- lmp/jobserv.yml
> lmp: drop support for dragonboard 410c/820c

- lmp/ota.sh
> lmp: ota: fix typo

- lmp/host_tests.py
- lmp/jobserv.yml
> lmp: drop support for rpi0-wifi

- lmp/host_tests.py
- lmp/jobserv.yml
> lmp: drop support for hikey

- lmp/bb-config.sh
> lmp: add support for custom SOTA_CLIENT

- lmp/jobserv.yml
> lmp: Add build for aktualizr-lite target

- lmp/jobserv.yml
> lmp/jobserv.yml: re-add RaspberryPi 4 32-bit build

- lmp/bb-config.sh
This will help provide the OE build logic more context as to what its building.
> lmp: Add some factory related variables

- factory-containers/docker-app-publish.sh
- factory-containers/ota-dockerapp.py
- factory-containers/test_build.sh
- factory-containers/test_tagging.py
- lmp/customize-target
- lmp/test_tagging.py
> factory-containers: Add support for advanced tagging

- factory-containers/build.sh
Related to commits:
94d246cbea0ff761febe8342285de8e5ed70ca06
a293cc1f70e0641921fa26b683d4a1b4c202dc60
> factory-containers: Fix caching logic for advanced tagging

- lmp/bb-config.sh
- lmp/customize-target
> lmp: Support installed_versions in customize-target

- lmp/bb-config.sh
Allow building a special lmp build variant which includes the ptest
packages by default, but via a special tag in order to avoid
contaminating the base builds.
This is done by simply changing the OTA_LITE_TAG variable and appending
-ptest to the lmp-based tags, which is later consumed by the build and
published under a different tag than the one originally intended.
Using a different tag for the ptest-enabled builds allows the user to
easily switch to the ptest tag when performing the OE package testing,
and move back to the base image once that is concluded.
> lmp/bb-config: add support to build ptest lmp variants via tags

- factory-containers/build.sh
- factory-containers/docker-app-publish.sh
- factory-containers/ota-dockerapp.py
- factory-containers/publish-compose-apps
- helpers.py
- lmp/customize-target
> containers: Add option to publish compose apps

- factory-containers/publish-compose-apps
> containers: Fix indexing image parts

- factory-containers/docker-app-publish.sh
- factory-containers/ota-dockerapp.py
> containers: Fix for the compose-app only case

- lmp/customize-target
> Explicitly specify Target format

- factory-containers/build.sh
This will allow jobserv to print the %complete while a run is active
> containers: Print out progress

- factory-containers/assemble-system-image
> containers: Specify Targets to assemble a system image for

- factory-containers/assemble-system-image
> containers: Shortlist apps for preloading

- factory-containers/assemble-system-image
> Preload uncompressed docker image data

- factory-containers/jobserv.yml
> containers: Build factory apps as compose apps

- factory-containers/publish-compose-apps.py
> containers: Add docker to compose apps conversion

- lmp/customize-target.py
> lmp: Tolerate absence of the overrides repo

- factory-containers/jobserv.yml
> containers: Switch the lmp container build to compose-apps

- factory-containers/jobserv.yml
> containers: Split the publish app job into two jobs

- assemble.py
- factory_client.py
- helpers.py
Preload can take a while to run. This helps add some rough progress
tracking. We could take this and make a small jobserv change so that
these CI runs could start showing percent done in the UI.
> container preload: Add some progress tracking

- apps/apps_publisher.py
This allows us to take service lines like:
foo:
image: hub.foundries.io/${FACTORY-andy}/foo
and evaluate them properly. It also pulls in an update from
compose-publish that allows us to get the sha from a file rather than
trying to scan stdout for it.
> containers: Pull in updates for compose-publish

- assemble.py
> preloading: shortlist apps in any use-case

- helpers.sh
We are seeing occasional hangs where repo-sync calls git which calls
some git-fetch command that seems to hang forever. The root issue
is bad international networking. This change attempts to deal with it
by:
* placing a reasonable timeout on a repo-sync command
* retrying a few times if the sync failed due to a timeout
> helpers: Wrap repo-sync with timeout and retry

- lmp/jobserv.yml
Signed-off-by: Tim Anderson <tim.anderson@foundries.io>
> lmp/jobserv: add ti am64xx-sk device to build

- apps/apps_publisher.py
> apps: tag lmp apps if lmp CI build

- apps/apps_fetcher.py
> preload: continue running CI job if preloading fails

- lmp/jobserv.yml
Include also the mfgtool target.
Signed-off-by: Daiane Angolini <daiane.angolini@foundries.io>
> lmp/jobserv: add imx6ullevk-sec to the machine target build list

- helpers.py
- lmp/generate-static-deltas
This is based on a project definition the ota-lite api creates
> lmp: Add script to generage static deltas

- apps/build.sh
DOCKER_SECRETS is starting to mean two different things:
* use buildx
* and optionally build container with secrets
This splits up the values so you can do a DOCKER_BUILDX without doing
the secrets.
> containers: Fix DOCKER_SECRETS variable (ab)use

- apps/login_registries
> apps: Enable Google Artifact Registry authentication

- apps/docker_registry_client.py
- apps/login_registries
- apps/target_apps_fetcher.py
- lmp/bb-config.sh
- lmp/build.sh
- preload-apps.sh
- preload_apps.py
- Added params for the OE-builtin App preload to bb-config.
- Added script to do the OE-builtin App preload
- Tiny refactoring needed for the OE-builtin App preload.
> Preload apps within oe

- assemble.py
> assemble: Sleep longer and retry more

- lmp/jobserv.yml
Signed-off-by: Tim Anderson <tim.anderson@foundries.io>
> lmp: add am62xx-evm

- lmp/bb-config.sh
- lmp/build.sh
- lmp/fetch-root-meta.sh
- lmp/fetch_root_meta.py
Fetch and store root metadata on an ostree-based rootfs during bitbaking.
> Fetch root meta

- apps/publish_manifest_lists.py
> apps: Fix tagging of the manifest list elements

- apps/compose_apps.py
> apps: Use the golang compose CLI tool

- apps/generate_non_factory_sboms.py
- tests/test_lmp_tagging.py
> apps: Fix sbom scanning for armv7

- assemble.py
We've been fighting losetup for a while thinking it was some issue with the WIC file not being flushed to disk. Turns out the ENOTEXIST error was actually from a missing /dev/loopX node. This shuffles things around to make the dirty bits more isolated.
> assemble.py: Fix sporadic losetup issue

- lmp/jobserv.yml
Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>
> lmp/jobserv: add imx8mm-ddr4-evk machine

- lmp/jobserv.yml
Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>
> lmp/jobserv: add support for imx8mn-ddr4-evk-sec

- lmp/jobserv.yml
- lmp/jobserv: add lmp-mfgtool to main-next post-merge
- lmp/jobserv: update main-next post-merge machine list
> Update main-next jobs list

- lmp/jobserv.yml
> lmp: enable builds for jetson-agx-orin-devkit

- helpers.sh
Temporary workaround for
https://bugs.chromium.org/p/gerrit/issues/detail?id=16355.
> helpers: use fixed revision v2.29.2 for repo

- apps/build.sh
A customer is doing some advanced unit-testing with their containers that we haven't seen before. This changeset introduces a bug fix and an enhancement to better service them.
> containers: Fix junit test problems

- lmp/jobserv.yml
Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>
> lmp/jobserv: add Code Review mfgtool build for imx8mn-ddr-evk*

- lmp/jobserv.yml
Add STM32MP15 Evaluation (secure boot) target.
Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>
> lmp/jobserv: add stm32mp15-eval-sec target

- lmp/jobserv.yml
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>
> lmp/jobserv: add Code Review base targets for imx6ul*

- helpers.sh
- lmp/bb-config.sh
- lmp/build.sh
- tests/test_lmp_base_version.sh
> helpers: set_base_lmp_version: work on a copy of the git repo

- lmp/build.sh
> lmp: build: publish aiotflash.tar images for mediatek devices

- assemble.py
- factory_client.py
- requirements-dev.txt
- tests/test_factory_client.py
- unit-test.sh
Fallback to a `.ext4` system image usage if `.wic` is not found for apps preloading.
> Preload to ext4

- apps/docker_registry_client.py
Obtain a JWT token for authN and authZ at Registry in the specification compliant way.
> apps: registry: Do auth as described in the spec

- lmp/jobserv.yml
As discussed at the "2023 AGP - LmP Hardware / BSP support review" session.
> lmp: reduce target list

- apps/build.sh
- apps/docker_registry_client.py
- apps/generate_non_factory_sboms.py
- apps/publish.py
- apps/publish.sh
- apps/publish_manifest_lists.py
- apps/target_manager.py
- assemble-system-image.sh
- helpers.py
- helpers.sh
- lmp/bb-config.sh
- lmp/build.sh
- lmp/customize-target.py
- lmp/fetch_root_meta.py
- lmp/update-targets
- tests/test_container_tagging.py
- tests/test_lmp_tagging.py
- tests/test_manifest_list_publishing.py
These changes allow us to run CI jobs against services not under foundries.io.
> Updates to support configurable URLs to our backend

- lmp/jobserv.yml
Add STM32MP15 Discovery Kit (secure boot) target.
> lmp/jobserv: add stm32mp15-disco-sec target

- .github/workflows/unit-tests.yml
- apps/target_apps_fetcher.py
- unit-test.sh
Set `--retry-times` parameter for the `skopeo` command so it will retry image/layer pulling 3 times if it fails.
> apps: Retry if image pull fails

- lmp/jobserv.yml
Folluwup of the https://github.com/foundriesio/ci-scripts/pull/373 to remove some pending stuff
> fixup! lmp/jobserv: temporarily drop from github_pr the deprecated machines

- lmp/build.sh
It will be usefull for debug broken builds
> lmp/build: print a status in each step of the post build processing

- lmp/jobserv.yml
- drop mfgtool
- drop imx8mm-lpddr4-evk in lmp-wayland
> cleanup main build
