- lmp/build.sh
Build system is now creating both wic and wic.gz image files so change
build.sh to publish only the compressed version.
> lmp/build.sh: publish only compressed wic files

- lmp/jobserv.yml
qemuarm64 is now supported in LmP.
> lmp/jobserv: add builds for qemuarm64

- zmp-samples/fota-compile.sh
This fixes make errors when building mcuboot and sample.
> zmp-samples/fota-compile: prefer west configfile for settings

- zephyr/jobserv.yml
The underscore is causing issues, so replace it with a dash:
zephyr-nrf52840-pca10056
> zephyr/jobserv: fix 840dk sanity worker tag

- zmp-samples/fota-compile.sh
- We auto select NET_DHCP4 on K64F now
- Andy won't be running CI for K64F
> zmp-samples/fota-compile: remove extra CI settings for K64F

- zephyr/sanity-device.sh
PyOCD is the only runner that we support for sanity flashing.  Let's
make sure we use it.
> zephyr/sanity-device: always use pyocd to flash sanity tests

- zephyr/sanity-device.sh
We still only support pyocd, but we need a better way to set the
runner.  Using custom parameter: --west-runner.
> zephyr/sanity-device: use --west-runner to specify pyocd

- zephyr/jobserv.yml
> zephyr/jobserv: extend timeout to 60

- lmp/host_tests.py
Add logic to check if core systemd jobs are active after boot.
Services currently validated:
- systemd-networkd-wait-online.service
- systemd-timesyncd.service
- aktualizr.service
> lmp: host_tests: check core systemd jobs

- zephyr/jobserv.yml
With the switch to nRF52840-DK, we've noticed several tests failing
in sanitycheck.  Most of these are due to specific needs for these
tests.  IE: the USB tests require that the nRF USB be connected during
testing, the led_lp5562 test requires a specific LED be connected via
I2C, etc.
The exception to this is the nffs_fs_api/large test, which needs more
investigation, but is also not working upstream.
> zephyr/jobserv: mark some more tests as flaky

- factory-containers/build.sh
- factory-containers/docker-app-publish.sh
- factory-containers/ota-dockerapp.py
- factory-containers/test_build.sh
These are the scripts I've been using for building multi-arch containers in CI and then having their corresponding docker-app(s) published into an OTA targets.json.
> Add scripts for "factory containers"

- lmp/bb-config.sh
- lmp/copy-previous-dockerapps
This allows us to grab the latest docker apps by finding the previous
build and then including them in this build.
> lmp: Add ability to add docker-apps into build

- lmp/jobserv.yml
AKLITE_TAG defaults to "promoted" and is used for generating the
sota.toml used in our release images. This keeps our premerge builds
from using that tag.
> lmp: Use AKLITE_TAG for premerge builds

- lmp/bb-config.sh
Expose AKLITE_TAG to the build so it can be consumed by bitbake.
> lmp/bb-config.sh: expose AKLITE_TAG to the build

- factory-containers/build.sh
This should give us a few improvements:
- use the --cache-from build flag to speedup rebuild
- detect when container files have changed, then trigger a build
- if the build has not changed, retag the images so that the dockerapps can be published
> factory-containers: add caching speedups, and modification detection.

- lmp/jobserv.yml
* Drop support for cl-som-imx7 and cubox-i
* Only build 64 bit version of the rpi4 build
> lmp/jobserv.yml: reduce number of builds

- factory-containers/ota-dockerapp.py
The issue can be seen  with CI build 659:
https://ci.foundries.io/projects/lmp/builds/659/
The customize-target script picked the docker-apps from build 649 to
copy into the new 659 target. We were expecting the containers from
the latest container build 656. The problem is that build 656 looked
at the previous LMP build which was a "premerge". This caused the
`custome-targets` script to fail because the OSTREE_BRANCHNAME names
differ between pre and post merge builds.
> factory-containers: Fix issue with "add-build"

- factory-containers/build.sh
This introduces a new docker-build.conf: EXTRA_TAGS_<ARCH>. This can
be used as follows:
SKIP_ARCHS="arm64"
EXTRA_TAGS_ARM="arm64"
This example would skip building a container for arm64. However, it
would tag the 32-bit image with -arm64 so it could run there as well.
> factory-containers: Add expanded tagging support

- factory-containers/build.sh
To avoid the case where the OLD_TAG image wasn't built, use the latest tag for cache instead. This should avoid use having to rebuild an image without cache if something happened to the previous build.
> factory-containers: drop OLD_TAG for latest reference

- factory-containers/build.sh
If we cannot obtain a git diff, rebuild the container.
> factory-containers/build: gracefully handle git diff

- factory-containers/build.sh
The tag "latest" was hardcoded, when we should have been using the ${LATEST} in case tags are set.
> factory-containers/build: make caching aware of OTA lite tags

- lmp/jobserv.yml
Similar to build-release, but following the lmp-manifest stable branch
(currently zeus). AKLITE_TAG and OTA_LITE_TAG also extended with -stable.
> lmp/jobserv.yml: add job for build release stable

- lmp/jobserv.yml
Change the current stable job to reuse the containers
available in postmerge, as we currently don't have a need
to split the containers into latest and stable.
This takes advantage of the new advanced tagging support
feature.
> lmp/jobserv: stable: use containers from postmerge

- factory-containers/build.sh
JobServ puts all project defined secrets as files under /secrets. This change allows a user to *securely* pass these secrets into a docker build context so that they may be used to do things like grab binaries from a secure registry.
> Allow containers to use secrets defined in JobServ

- factory-containers/build.sh
- factory-containers/docker-app
- factory-containers/docker-app-publish.sh
- factory-containers/ota-dockerapp.py
- helpers.py
This change allows factories to optionally start building docker-app bundles when setting `DOCKER_APP_BUNDLE=1`. When set, in addition to producing targets.json items like:
~~~
"custom": {
"docker_apps": {
"filename": <TUF Target Name>
}
}
~~~
We'll also produce a multi-arch friendly docker-app with a new field "uri". With a properly functioning version of aktualizr, a device will be able to install the app using the docker-app bundle from the hub.foundries.io registry rather than the TUF reposerver .dockerapp file. This is nice and will eventually allow us to stop publishing all these tuf targets for .dockerapp files (make the targets.json a lot smaller).
There's also a subtle check in this change to allow us to stop producing these .dockerapp TUF targets by a factory converting their …
> Add optional support for publish docker app bundles

- lmp/jobserv.yml
There are two issues with tagging and discovery of docker apps for
premerge builds:
1) The OTA_LITE_TAG is incorrect. We have the new advanced tagging
format which allows us to specify this correctly now.
2) Our lmp/customize-target can't find the previous version of the build
because we are using a different OSTREE_BRANCHNAME for premerge
builds. This is a relic and isn't needed anymore, so we can just give
everything the same branchname.
> lmp: Fix premerge tagging

- factory-containers/build.sh
Buildkit produces "inline" images which include the build cache and runtime imaged bundled as one. To properly use this cache during a buildkit build, we need to pass the flag BUILDKIT_INLINE_CACHE=1.
https://github.com/moby/moby/issues/39003
> buildkit: use BUILDKIT_INLINE_CACHE=1

- factory-containers/ota-dockerapp.py
- lmp/customize-target
This change helps track the code source SHA's that produce a given
target. This will be useful for tools like fioctl, the webui, and the
lmp platform itself.
> Include source shas in TUF Target

- lmp/bb-config.sh
As per:
https://github.com/foundriesio/meta-lmp/pull/167
> lmp: Provide default tag to lmp-device-register

- lmp/jobserv.yml
Only enable ptest-based builds for intel and rpi3-64 at this stage so we
can validate the ptest build and tagging process.
> lmp/jobserv: add ptest variants for intel and rpi3-64

- lmp/bb-config.sh
It should go with https://github.com/foundriesio/meta-lmp/pull/177
> containers: Add a conf var to turn on compose app

- factory-containers/build.sh
We hit a bug with a containers.git layout like:
~~~
container/
Dockerfile
docker-build.conf
other-file
~~~
docker-build.conf has:
BUILD_CONTEXT="../"
This means a change to "other-file" should produce a new container, but
our logic for seeing what changed in the container did not take into
acount this BUILD_CONTEXT.
> containers: Include BUILD_CONTEXT for detecting changes

- lmp/build.sh
During processing of repo init command we strip potential "-b <ref>"
passed into REPO_INIT_OVERRIDES.  The current logic is:
remove "-b" + <any white space chars> + <any word chars>
If there's a hyphen in the <ref> it thinks this is a new word and
stops removal there.
So if REPO_INIT_OVERRIDES is:
-b home-assistant -m test.xml
We get:
-assistant -m test.xml
To fix this, let's change the removal logic to:
remove "-b" + <any whitespace chars> + <any non-whitespace chars>
This means stop the removal at the next occurance of a whitespace char.
> lmp: build: fix stripping -b <ref> when hyphen is present

- factory-containers/assemble-system-image
- factory-containers/assemble-system-image.sh
- factory-containers/compose_app_downloader.py
- helpers.py
If container images of Compose Apps are not found on
a local NFS/share/folder then try to download/dump them
during assembling of a system image with "pre-loaded" conatiners.
> containers: Dump container images if not found

- factory-containers/publish-compose-apps
We don't always catch compose syntax errors and when we do, the error
messages aren't always obvious. This should help by using the actual
compose tooling.
> containers: Validate content of docker-compose file

- factory-containers/assemble-system-image
The wic image is created with a small overhead of free space. We should
increase the wic file's size to account for the amount it will grow by
when adding the tarfile into it.
> containers: Resize wic before copying tarfile

- create-creds
- factory-containers/docker-app-publish.sh
- helpers.py
- lmp/bb-config.sh
This change allows us to set the client_secret value of credentials.zip
during each build. This will allow us to remove this client_secret
value making the credentials.zip file a little more secure.
> lmp: Support dynamically scoped token in creds.zip

- factory-containers/build.sh
Run a pre-build script before any image build configuration.
> Source pre-build.conf before trying to find images

- lmp/update-targets
This was in the ota-lite repo and used to handle the `fioctl targets
tag` command. Its getting complex enough to live in ci-scripts where
we can take advantage of common code.
> lmp: Add update-targets script

- factory-containers/build.sh
If a container includes a file like:
container-foo/.docker_build_args
We'll add those key=values to our docker build command. This file
could be static or generated at runtime via docker-build.conf
> containers: Add a method to add docker build args to container

- lmp/jobserv.yml
- drop ota / ptest build for rpi3-64
- drop supported / other from build names (all valid targets are
supported)
- sync machine list with the supported list from lmp
> lmp: clean up public jobs

- assemble.py
On wic-based image installers we don't have the entire installed target
base dir path created (only the root ext4 image), so make sure to create
the required dirname when writing the updated installed_versions file.
This won't cause any difference on the traditional wic images and will
make the required path/file to be available for the wic efi installer
(which will then copy over to the right location while performing the
install process).
> assemble: make sure installed target base dir exists

- assemble.py
Use correct matching loop device id while parsing the output of losetup
-a, otherwise it will just try to use the first loop device available to
the system.
> assemble: fix loop device id

- assemble.py
Mark correctly the currently installed Target. `is_current` attribute should be an attribute of Target not a collection of Targets.
> lmp: Correctly mark currently installed Target

- lmp/bb-config.sh
lmp-device-register is now able to be configured dynamically by ci,
so set the required arguments based on the factory values.
This also introduces LMP_DEVICE_API, which can be customized by the
factory config.
> lmp/bb-config: set lmp-device-register custom factory arguments

- apps/build.sh
Due to docker rate-limiting we now need an authenticated read-only
docker hub account to help keep us from hit docker rate limits.
We added this into jobserv:
https://github.com/foundriesio/jobserv/commit/eb8a3cba17194541a58939cbbee48ee91f7359d5
> containers: Pull in host config when present

- lmp/build.sh
Cover a few extra boot firmware files, and avoid publishing files used
by iMX in case the build is mfgtool, to avoid confusion.
> lmp/build.sh: clean up publishing to the root of the archive

- lmp/preload-app-images
This is just a tiny clean-up, the first step towards removing of `arch` param. It's become useless since we have `arch` attribute in a target json. 
> preload: Make 'arch' param optional

- lmp/bb-config.sh
- lmp/customize-target.py
- tests/test_lmp_tagging.py
Drop the need for exporting variables from local.conf as that causes a
massive bad side effect on caching.
Move variables to be provided as parameters for the customize-target
script instead, and drop variables that are not used by LMP.
> lmp/bb-config: drop exports from local.conf

- lmp/bb-build.sh
- lmp/bb-config.sh
- lmp/bb_logconfig.json
- lmp/build.sh
Add logic for handling a custom config log that improves the standard stdout output by adding timestamp and redirects the warn/debug information into 2 files, which are later uploaded as part of the build process.
You can see how it looks like by checking https://ci.foundries.io/projects/rsalveti-v77/lmp/builds/9/n1sdp/artifacts/console.log.
> lmp: add custom debug config log and publish debug/warning

- apps/apps_publisher.py
Yield a meaningful error message if
1. `image` element is not found in a compose app service configuration (docker-compose.yml:service);
2. image URI refers to an image that does not belong to the given Factory.
> Improve error logging

- lmp/build.sh
Publish Secondary Image Table (needed for redundant boot) and
HDMI firmware for iMX8MQ.
Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>
> lmp: publish sit and hdmi firmware images

- lmp/jobserv.yml
The trigger sends POST request to Conductor which runs the testing rig.
The test merge happens in all "testing" factories. Successful manifest
merge will trigger automated testing round.
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@foundries.io>
> lmp/jobserv: trigger test merge after successful build

- apps/compose_apps.py
We currently only look for `docker-compose.yml` files. This can be
confusing to a user that creates a `docker-compose.yaml`.
This isn't the cleanest approach, but our code expects
docker-compose.yml in a couple of places. This fixes things in the
least invasive way.
> apps: Handle publishing for docker-compose.yaml files

- lmp/generate-static-deltas
Don't create 'objects' folder, it became not mandatory since
https://github.com/foundriesio/ostreehub/commit/b5a9e11750e29dcd225aa9f7ba76c6cd0a1bc64b
> lmp: delta: no 'objects' folder is required

- apps/build.sh
Now that we have enabled buildx, we publish the build cache each CI run.
We can remove the complex logic to figure out which app changed, and just
use the build cache we are already pulling in.
> apps/build: use buildx caching

- apps/build.sh
Testing shows that using --label="..." with a different value
each time you run a build will generate a different manifest sha
when pushed to a registry.
This label is used to identify the build a particular image was
created in.  For now, let's drop the label and investigate a
better way to identify images on hub.foundries.io (if at all).
> apps: build: drop image label to fix manifest sha

- apps/build.sh
- apps/publish.sh
In commit ab7f7f05b77490dce039d9ae68d5b215c5ba15c3 we stopped including
the build number in the container metadata. hub.foundries.io is using
that data to understand what build number (Target version) produced the
container. This change adds the build number into the container image's
tag so that we can infer it.
> containers: Include build number in container tag

- assemble.py
If you have a container build producing targets based on multiple
platforms we were using the same file name and overwriting the work we'd
done.
> containers: Handle advanced tagging for prebuilt images

- apps/target_manager.py
- tests/test_container_tagging.py
Inheriting from the LmP build is a little confusing to users as they'll
see a createdAt timestamp in the past and a URI that doesn't point to
the CI job that created this Target.
> containers: Include more accurate TUF custom data

- apps/build.sh
Docker can change this and it can break us. We are currently seeing
the latest "stable" breaks armhf. This pins us to the stable tested
version we've been using. We can then upgrade when we choose.
> containers: Pin version of buildkit

- apps/build.sh
Create a md5sum list of all files used in the container build context. This is helpful for tracing caching issues.
> factory-containers: add md5sum collection

- apps/publish.sh
There is no need in dumping and storing of Apps and their images on NFS
storage since their injection into a system image has been moved from
the LmP/bitbake run to separate dedicated run that can dump images by
itself.
> apps: don't preload and store Apps

- assemble.py
Currently the assemble wic script uses a hard-coded value of 2 for resizing the rootfs.
This is not always true.
Let's use the last line of the `fdisk` output as a guide for the last partition (which is the only one that can be resized anyway).
> assemble wic: drop hard-coded partition used for resizing

- lmp/jobserv.yml
Use the new names as available starting from OE / Yocto hardknott.
> lmp/jobserv: update imx8mm and imx8mq machine names

- apps/build.sh
The spot this was done contains the BUILD_CONTEXT from the
docker-build.conf file, "../", rather than the:
BUILD_CONTEXT="$REPO_ROOT/$x/"
we set a few lines above this.
> containers: Fix logic for md5sums with custom BUILD_CONTEXTS

- apps/build.sh
- apps/login_registries
- apps/publish.sh
- assemble-system-image.sh
Factories may be configured with private container registries. CI
will set these with a "secret" that we can execute to login with.
> containers: Add logic for private container registries

- apps/publish.sh
- create-creds
- helpers.py
- lmp/bb-config.sh
- lmp/create-creds
- lmp/generate-static-deltas
- lmp/update-targets
JobServ now sends us the target.sec file. This means there's no need
to rely on the contents of an NFS copy of credentials.zip.
> Move to using totally dynamic creds.zip

- lmp/build.sh
We might have variants of imx-boot (e.g. nohdmi), so make sure
we're publishing all of them together at the root folder.
> lmp/build.sh: publish all imx-boot-machine files

- lmp/bb-build.sh
Customer's may have bitbake recipes referencing private ssh+git
repositories. This change allows users to configure Factory support by
naming convention with fioctl-secrets. For example a user can create 2
secrets:
ssh-github.key - content coming from ssh-keygen (i.e id_rsa)
ssh-known_hosts - the fingerprint(s) of the server to be connected to
If these are detected, the bitbake build process will launch ssh-agent,
ssh-add the key(s), and set the known_hosts file so that git-clones
won't prompt for user input.
> lmp: Add ssh-agent support for recipes

- apps/apps_publisher.py
- apps/publish.py
- tests/test_apps_publisher.py
- Pass a list of platforms (aka architectures) defined in factory-config.yml::containers::platforms, aka factory architectures) to the compose publish tool, so it can shortlist architectures supported by App's images. Otherwise, CI might publish App that supports non-factory architectures what might lead to subtle issues while running App/containers on a device. 
> apps: pass arch list to the publish tool

- lmp/jobserv.yml
Include also the mfgtool target.
Signed-off-by: Tim Anderson <tim.anderson@foundries.io>
> lmp/jobserv: add imx6ulevk to the machine target build list

- helpers.sh
- lmp/bb-build.sh
- lmp/build.sh
Users have both private recipe repositories and private layers. We
have to run two different agents because we repo-sync as root and run
the OE build as "builder".
> lmp: Use ssh-agent for repo-sync and OE build

- apps/login_registries
The secret contents is expected to be in the format:
<azure pricipal id>:<azure principal password>
docs.fio will include a corresponding example
> containers: Add support for Azure private registry

- apps/docker_registry_client.py
- apps/target_apps_fetcher.py
- Fix DockerRegistryClient::parse_image_uri so it accepts image URIs
that contains one or more elements in the `name` (aka `path`) field
of an image URI. E.g. fiotesting1.azurecr.io/alpine@sha256:<hash>,
fiotesting1.azurecr.io/library/alpine/latest@sha256:<hash>.
- Adjust DockerRegistryClient::parse_image_uri to the new parsing logic,
`factory` and `app` fields are mandatory only for images stored in hub.f.io.
- Added unit tests for image URI parsing logic.
> apps: align image URI parsing with OCI dist spec

- lmp/bb-build.sh
- lmp/bb-config.sh
- lmp/bb_logconfig.json
- lmp/build.sh
It is quite hard to identify build errors (that are not parsing related)
at the moment, since we don't save the environment and the build log is
only available on successful builds.
Fix by making sure the core files are always stored under ${archive}, as
that folder is always uploaded, even on errors.
> lmp: deploy env and logs even in case of failures

- lmp/bb-build.sh
Failures during setscene are not critical for the build as bitbake can
later rerun those tasks without cache, so separate into a dedicated call
and in a way that won't abort the job execution.
> lmp/build: split setscene from main bitbake call

- lmp/bb-config.sh
It allow the variable DEV_MODE to be set as a lmp:params: stanza and
added on the local.conf to be used as needed.
Signed-off-by: Daiane Angolini <daiane.angolini@foundries.io>
> lmp: Add DEV_MODE variable to be handled on local.conf

- assemble.py
If "restorable" apps are set for factory then preload both
types of Apps in order to make the early App startup work without
a need to do any device registration before.
> preload: Preload both compose and restorable Apps

- assemble.py
Sync while writing to a system image file (fsync flag for `dd`) and after running `parted` to resize the file based partition.
> assemble: Sync FS once a system image been resized

- lmp/bb-build.sh
This will add the option to change the default bitbake arguments using the variable `BITBAKE_EXTRA_ARGS` 
NOTE: currently in the version we have it is already possible to change the default with:
```
ci_scripts:
url: https://github.com/quaresmajose/ci-scripts
git_ref: wip
```
> lmp: add BITBAKE_EXTRA_ARGS to use additional the bitbake arguments

- helpers.sh
- lmp/build.sh
== 2022-06-08 13:38:05 Build triggered by change to lmp-manifest
++ pwd
+ manifest='file:///repo/.git -b cfad3167070e3783cac8c6260e9efa63c952e56c'
+ git branch pr-branch cfad3167070e3783cac8c6260e9efa63c952e56c
fatal: unsafe repository ('/repo' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /repo
Script completed with error(s)
> lmp/build.sh: fix the safe.directory when running the simulator locally

- assemble.py
- Sleep before each `losetup` attempt.
- Retry up to three times if `losetup` fails.
> assemble: Sleep before and retry if losetup fails

- apps/target_apps_fetcher.py
Store an App's archive as a regular image blob in the app store's blobs
directory. It simplifies and unifies fetching of blobs/archives by
aklite/skopeo, specifically, it's useful for an offline update.
> apps: Store App's archive in the blobs dir

- apps/build.sh
- apps/publish.py
- apps/publish_manifest_lists.py
We've had a buggy way of creating multi-arch manifests since the
inception of this tool. This predated docker-manifest and the ability of
CI builds to access artifacts from another run. The issue is that we
build each platform concurrently. Therefore, we don't know which run
is going to complete last and be able to create the multi-arch manifest.
This lead to the ugly hack where we basically did:
docker manifest create && docker manifest push || true
Only the last run will actually publish the manifest. However, you
periodically have infra issues where the manifest push operation
actually fails. You don't *see* that and we move on the publish run
which will eventually fail to pin this multi-arch reference since it
doesn't exist. Then someone in support has to back-track to find the
source …
> apps: Clean up logic around multi arch manifests

- preload_apps.py
- Make sure that the `registry creds` secret file exists before loading
it into a dict.
> preload: Check if a registry creds file exists

- apps/build.sh
We have a customer using a private Google Artifact Registry instance
that's hit buildkit problems. Moving from 0.8.3 to 0.10.3 resolved them
at first. However, as they've added more containers to their factory, we
are seeing a need to create a new context to make them all build
correctly.
This change creates a context for each container and also makes it
easier for us to change what version of buildkit a customer uses.
> apps: Fix flaky issue with buildkit

- apps/publish_manifest_lists.py
- tests/test_manifest_list_publishing.py
apps: Improve image tagging at the publish step
- Improve the tagging logic so it takes into account the cases when e
ref/tag matches an App name and it contains dashes. Also, it should
fix other odd/edge cases.
- Add a unit test to cover edge cases.
> Fix tagging issue

- apps/compose_apps.py
> preload: Fallback to `docker-compose` if no `docker compose`

- apps/compose_apps.py
This reverts commit 5b931369c0cce7d2aee4fff2f2a842d0145d29c3 since `docker compose` is available in the `lmp-sdk` container now, see https://github.com/foundriesio/lmp-manifest/pull/208.
> Revert "preload: Fallback to `docker-compose` if no `docker compose`"

- lmp/jobserv.yml
Continue as much as possible after an error. While the
target that failed and anything depending on it cannot
be built, as much as possible will be built before
stopping.
> lmp/jobserv: run bitbake with --continue for github_pr

- lmp/jobserv.yml
> lmp/jobserv: the stable branch is now kirkstone

- lmp/bb-config.sh
fixes the following issue:
```
| ERROR: Nothing RPROVIDES 'linux-firmware-rpidistro-bcm43455' (but /srv/oe/build/conf/../../layers/meta-lmp/meta-lmp-base/recipes-samples/images/lmp-base-console-image.bb, /srv/oe/build/conf/../../layers/openembedded-core/meta/recipes-core/packagegroups/packagegroup-base.bb RDEPENDS on or otherwise requires it)
| linux-firmware-rpidistro RPROVIDES linux-firmware-rpidistro-bcm43455 but was skipped: because it has a restricted license 'synaptics-killswitch'. Which is not listed in LICENSE_FLAGS_ACCEPTED
| ERROR: Required build target 'lmp-base-console-image' has no buildable providers.
```
> lmp/bb-config: accepte the synaptics-killswitch license on raspberrypi

- lmp/jobserv.yml
Use kirkstone machine names for stm32mp1.
Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>
> lmp: use kirsktone machine names for stm32mp1

- apps/build.sh
We have a problem with factories using a common base image as described:
https://docs.foundries.io/88/reference-manual/docker/containers.html#id1
Currently, every build is causing the images that extend the base image to be "rebuilt". I say that in quotes because its still the same image: every single layer the image is made from remains the same. However, the docker manifest pointing to the layers does change.
This comes from my misunderstanding of the "FROM" line in the child containers. Our docs have have basically inherit from base:${tag}-${arch}. ${tag} is changing every single build. While the SHA256 it points to does not change, the logic of a Dockerfile to decide what to build more or less does a string equals comparison of each line of the Dockerfile. This causes things to …
> apps: Build containers with two labels

- apps/publish_manifest_lists.py
- tests/test_manifest_list_publishing.py
Our logic was hard-coded to assume Git SHA's are always 7 long. Git SHAs can sometimes collide in the first 7 characters leading the hash to be longer.
This change dynamically determines the SHA length so that we can handle all input.
> apps: Handle git-sha collision bug in tagging

- lmp/build.sh
Ota-ext4 can be quite big depending on the machine used (e.g. jetson agx has a 28GB ota-ext4 file), so make sure to remove it if the compressed format is available.
> lmp/build: remove ota-ext4 when ota-ext4.gz is available

- helpers.sh
Fixed v2.29.2 had issues when doing repo sync inside the container.
> helpers: repo: temporarily use main for another attempt to fix 16355

- helpers.sh
Used a pinned version release to avoid issues with unexpected upstream releases breaking us.
> helpers: repo: use fixed v2.29.4 release

- lmp/bb-config.sh
`SOTA_TUF_ROOT_PROVISION` was hardcoded to `1`. This change fixes it and allows overriding its value in factory config.
> lmp: bb-config: Allow `SOTA_TUF_ROOT_PROVISION` overriding

- apps/build.sh
Our logic for building containers predates buildx. We eventually started doing buildx and moving customers over one by. Turns out, we didn't migrate one of our oldest customers. They are now needing something buildx offers. This change set makes us use buildx. It's safe because everyone else was already on it. While enforcing buildx, I was able to remove a lot of old conditional logic that simply can't be run now.
> Enable buildx explicitly and remove legacy logic

- lmp/jobserv.yml
This reverts commit 76f9596a83856c48a6ca9a6a13bc6fac4c0a1d98.
We don't publish targets anymore.
> Revert "lmp/jobserv.yml: install aktualizr-lite-public-stream by default"

- lmp/bb-config.sh
> lmp/bb-config: use EXTRA_IMAGE_INSTALL when they have content

- lmp/build.sh
Some customers may put tags in their lmp-manifest repo which will can cause us to get the wrong cache value
> lmp: Get version tag from LmP repository

- helpers.sh
- lmp/build.sh
- tests/test_lmp_base_version.sh
Its a little tricky to pick up the base LmP version. We need to make sure we've fetched tags from the public LmP and *don't* look at tags that have been created by the user.
The old version was also getting the *latest* tag which is currently v89 but that's probably not the actual LmP version the customer is building with. Git doesn't have a way to distinguish where tags come from, so the easiest thing to do is just delete all the tags and then pull from our official tags.
> lmp: Fix logic for detecting the base version

- apps/publish.sh
The newer version of `garage-sign` does not refresh targets meta expiration by default as it's used to be in the older versions. So, let's set the expiration value to one month explicitly in the `garage-sign` command call.
The same already happens in the LmP build too, see `meta-updater/classes/image_types_ostree.bbclass`.
> apps: Set default targets expiration to one month

- helpers.sh
Sometimes repo init fails sporadically and this will abort the ci job.
To avoid such situation we can try again to run the command with a random sleep in between.
```
|== 2023-01-11 21:29:51 Running: repo init --repo-rev=v2.29.4 --no-clone-bundle -u file:///repo/.git -b baaff135ea1b0d04f6657944d755a14c1f772d72 |  repo: error: "git" failed with exit status 128
|    cwd: /srv/oe/.repo/repo
|    cmd: ['git', 'fetch', '--quiet', 'origin', '+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*']
|    stderr:
|    >> fatal: unable to access 'https://gerrit.googlesource.com/git-repo/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
|  fatal: cloning the git-repo repository failed, will remove '.repo/repo'
|  Downloading Repo source from …
```
> helpers: re-run repo init on loop to avoid ci failures

- factory_client.py
Remove leading and trailing `"` symbol from the `VERSION` value extracted from `os-release`.
For some reason, the LmP started adding them recently.
> preloading: Strip quotation mark in VERSION

- lmp/jobserv.yml
No need for provisioning TUF metadata on the public lmp factory, we don't publish targets anymore.
> lmp/jobserv: disable SOTA_TUF_ROOT_PROVISION

- lmp/jobserv.yml
> lmp/jobserv: in yaml, strings don't need quotes but numbers do

- lmp/bb-build.sh
If we have failing setscene tasks is because our sstate cache is broken and needs to be fixed. When this happens bitbake can take care of the of the failed setscene tasks running again the real task.
Running bitbake with '--setscene-only' doesn't help in this case because when the setscene task fails, the new one stored on the sstate-cache will only be updated after running the real task.
To do that bitbake needs to run without '--setscene-only', that is what is done on the on the second bitbake call, otherwise bitbake will get the setscene task again from the sstate-cache.
This also makes more clear the sstate-cache usage in the CI because currently is not possible to see it in a clear way because in the first bitbake call the sstate-cache reuse is 100% and on the second call is 0%.
The …
> lmp/bb-build: since lmp v87 the setscene-only is not need anymore

- lmp/build.sh
Handy to have both wic and the respective bmap file under the same root folder.
> lmp/build: also publish wic.bmap in the main root folder

- assemble.py
Our current logic requires shortlist and targets to be a comma seperated list with no spaces:
"1,2,3"
This change allows it to deal with whitespace like:
" 1, 2, 3 "
> assembly: Handle shortlist with spaces

- lmp/bb-config.sh
**Buildstats**
The buildstats option is only enabled on the CI build but it is very useful in local builds as well to check sstate-cache usage.
**Create-spdx**
The create-spdx is been moved to only runs on CI as local builds can run in the majority of time without this
that reduces the build time.
> LmP: refactor INHERIT build config

- lmp/bb-config.sh
Some tools like oe-selftest requires the full path as it runs on a relocated build path.
> lmp/bb-config: use the full path for the bb_logconfig.json

- lmp/bb-config.sh
When the length of SSTATE_CACHE_MIRROR is zero the check is not evaluated correctly.
Can be tested with:
```
T=$(mktemp)
cat << 'EOF' > $T
echo -
if [ -d "$1" ]; then echo " OK "; fi
if [ -d $1   ]; then echo "FAIL"; fi
EOF
sh $T /tmp
sh $T ""
sh $T 
```
> lmp/bb-config: fix zero length SSTATE_CACHE_MIRROR directory test

- helpers.sh
- lmp/bb-config.sh
- lmp/jobserv.yml
The variable `SSTATE_CACHE_MIRROR` is to force the use of the public LmP HTTP ssate cache mirror: 
```
params:
IMAGE: lmp-factory-image
SSTATE_CACHE_MIRROR: ""
```
The variable `LMP_VERSION_CACHE_DEV` is to use the development version of the cache: 
```
params:
IMAGE: lmp-factory-image
SSTATE_CACHE_MIRROR: ""
LMP_VERSION_CACHE_DEV: ""
```
> Adds support to use the HTTP sstate cache mirror on the factories

- lmp/bb-build.sh
- lmp/build.sh
This script [1] will write a summary of the buildstats to the terminal, sorted by start time or duration, optionally hiding short tasks, and highlighting long running tasks.
[1] https://git.yoctoproject.org/poky/commit/?id=1908193b81a1a5dbe04ccf296c2daa15bfac7000
> lmp/bb-build: run buildstats-summary at the end

- assemble.py
- factory_client.py
- helpers.py
Fetch and store Restorable Apps regardless whether the assemble run succeeds with Apps preloading or not.
Therefore, a user can download an apps tarball for offline update even if app preloading fails, e.g. a WIC image is not supported.
> Fetch apps unconditionally

- assemble.py
- factory_client.py
Don't preload compose Apps if restorable Apps are preloaded and LmP version is >= than 87.
LmP >= 87 includes the apps early startup scripts for restorable apps what makes compose apps preloading redundant/not needed.
The early startup script includes "image registration" at the docker store before running `dockerd` so the later becomes aware about images copied to the store by `skopeo copy` command.
> assemble: Skip compose Apps preloading if not needed

- lmp/build.sh
Useful for debugging possible boot command differences per builds.
> lmp/build: also copy boot.cmd if available

- lmp/generate-static-deltas
Pull an ostree commit file tree if a URL to an ostree repo archive is missing.
If an ostree repo is built not in a scope of the Foundries' CI then there is no archive with built ostree repo is available. In such cases, the given script will download an ostree objects from the Foundries's OSTree Service.
> Pull ostree if archive missing

- apps/build.sh
- apps/publish.sh
- helpers.sh
This consolidates the docker-login logic to a single helper.
This also changes the container build process only call docker-login once against hub.fio which is all that's needed. Calling multiple times has no effect. We are also long past the time you could run this script with "noauth", so I simplified the logic
> apps: Create a helper for docker-login

- assemble.py
Avoid uploading a broken image as part of the assemble image task (can take a massive amount of disk space as it is not compressed at this point).
> assemble: remove used image in case of failures

- lmp/bb-selftest.sh
- lmp/build.sh
The variable OS_SELFTEST will contain the oe-selftest arguments.
When the variable is defined on the factory-config.yml,
the oe-selftest will run with the arguments specified.
```
oe-selftest $OS_SELFTEST --newbuilddir $PWD
```
The results is also stored on the artifact folder
${archive}/selftest for post analysis.
So the following factory configuration will run the LmP reproducible test.
```
lmp:
params:
OS_SELFTEST: "--run-tests lmp_reproducible.ReproducibleTests.test_reproducible_builds"
```
> Add support to run the oe-selftest on the factory

- assemble.py
As the wic images are being modified as part of the assemble process, generate a bmap from the new image in order to allow users to flash the new images with bmaptool.
> assemble: generate bmap tool for the updated wic image

- lmp/build.sh
Per our slack conversation about the potential race condition when attempting to mount the lmp cache.
> lmp/build.sh: gracefully handle the creation of the cache dir

- assemble.py
Preload Apps to the dockerd store unconditionally even if the restorable apps are preloaded to the skopeo/OCI store.    
The reason for doing so is to optimize the timing of the app's "early" startup by eliminating the need to copy the app's data (layers/images) from the skopeo store to the dockerd store during the early startup process.
The copying process can be time-consuming on resource-constrained devices, as it involves untarring and decompression of data.
> Preload to docker unconditionally

- assemble-system-image.sh
- assemble.py
Fetch app images to the NFS sub-directory (NFS dir mounted to the container) by default.
Currently, app images are fetched to the container `tmp` dir mapped to a host's RAM. The host's RAM capacity can be lower than the overall size of extracted/pulled App images, hence we need to pull them into some other folder.
Not mapping the container's tmp implies that the tmp is based on the host's overlay2 FS (the CI run container FS); it doesn't work too because of the "overlay2 over overlay2 issue", dockerd cannot have a data root based on overlay2 FS.
Therefore, the only feasible solution left is to fetch app images to the NFS sub-directory which is mapped to a host's directory located on a NFS volume.
> assemble: Fetch apps to the NFS storage by default

- lmp/jobserv.yml
Our next release will move users to having an initial factory based on a "fast first target". This target will be the LmP prebuilt release image. These images currently set their default OTA tag as "postmerge". However, the new factories we create for people will be set to "main".
This change makes the tag "main" so that `lmp-device-register` will put the device on the correct initial tag.
> lmp: Move to "main" OTA tag

- lmp/jobserv.yml
This devices are not supported upstream on oe-core master branch
> lmp/jobserv: remove stm32mp15 devices from main-next

- helpers.sh
Required to unblock the development of v92 without populating v91 cache bucket with things not related to it.
> helpers: temporarily increase lmp cache by 2

- apps/apps_publisher.py
- apps/build.sh
- apps/docker_store.py
- apps/get_layers_meta.py
- apps/publish.py
- Parse the docker store to obtain a size and a disk usage for each App layer (unarchived).
- Store the obtained layer metadata as a CI run artifact. Then, it can be used by the CI publish run to add the layer metadata (disk usage & size) into App manifest.
- The embedded layer metadata can be used by the aklite/update client to determine whether an App update can fit into a device disk.
> apps: Parse the docker store to obtain layer size and disk usage

- lmp/bb-build.sh
- lmp/build.sh
In LmP build we have the buildstats enabled because we use the
INHERIT += "buildstats" but the output is hard to read and understand.
The openembedded-core pybootchartgui scripts can process this logs and
generates some pretty charts.
> lmp/build.sh: create bootchart.svg with the buildstats collected data

- helpers.sh
Relevant changes:
- c657844 main: Fix exitcode logging
- 1d3b4fb sync: Track new/existing project count
- be71c2f manifest: enable remove-project using path
- 696e0c4 update links from monorail to issuetracker
- b2263ba sync: Handle case when output isn't connected to a terminal
- 945c006 sync: Update sync progress even when _sync_dict is empty
- 71122f9 sync: Handle race condition when reading active jobs
- 07a4529 pager: set $LESS only when missing
- 1783332 Add envar to replace shallow clones with partial
- 04cba4a sync: Show number of running fetch jobs
- 3eacfdf upload: use f-string
- aafed29 project: Include tags option during fetch retry
- 90f574f Parse OpenSSH versions with no SSH_EXTRAVERSION
- 551285f sync: Show elapsed time for the longest syncing project
- 131fc96 [git_trace2] …
> helpers: update repo to v2.35

- lmp/bb-build.sh
- lmp/build.sh
First version of this PR https://github.com/foundriesio/ci-scripts/pull/286 have a bug because it uses `bitbake-getvar` and it is not avaliable before `kirstone` and was reverted:
- https://github.com/foundriesio/ci-scripts/commit/7a8772fbf09d9e5759ea9668de979f1ca463b7cb
- https://github.com/foundriesio/ci-scripts/commit/0c25b3ac34b2bb5e9389d0a7629941b2497301e7
The commit https://github.com/foundriesio/ci-scripts/commit/3913debb1bcc0502d49e4d80544ddb67f2dc0352 adress the issue and will checkif `bitbake-getvar` is available.
> lmp/build.sh: create bitbake_buildchart.svg with the buildstats collected data [V2]

- lmp/bb-build.sh
This reverts commit 40a0e96a47306e1f8d71722ccd073d6ab3fa751e.
There is still an issue pending that need the build in two steps. We have seen some failed builds with [1] where the bitbake build everything but the build fails at the end.
More investiagation is needed to root cause and fix the issue on the bitbake code base.
[1] `failed with exit code ‘1' - real task will be run instead`
[FFTK-2690]
> Revert "lmp/bb-build: since lmp v87 the setscene-only is not need any more"

- lmp/bb-build.sh
```
== 2023-08-08 11:10:06 Running: bitbake -p
|  Loading cache...done.
|  Loaded 0 entries from dependency cache.
|  Parsing recipes...done.
|  Parsing of 7680 .bb files complete (0 cached, 7680 parsed). 11906 targets, 2150 skipped, 20 masked, 0 errors.
|--
== 2023-08-08 11:13:12 get global and image specific environments
== 2023-08-08 11:14:57 Running: bitbake --setscene-only lmp-base-console-image
| Loading cache...done.
| Loaded 11906 entries from dependency cache.
| ...
|--
== 2023-08-08 11:19:24 Running: bitbake -D lmp-base-console-image
| Loading cache...done.
| Loaded 11906 entries from dependency cache.
| ...
|--
```
> lmp/bb-build: add the time bitbake requires to run

- lmp/bb-build.sh
The run function have significant overhead because it used the indent which in turn uses sed on every line.
So use the function status to show the build steps and call bitbake directly.
> lmp/bb-build: use status and call bitbake directly

- lmp/generate-static-deltas
- lmp/static_deltas.py
- requirements-dev.txt
- tests/test_deltas_generation.py
- tests/test_static_deltas_generation.sh
- Some refactoring and fixes required by the new functionality.
- Obtain and upload statistics about generated static deltas.
- Update each relevant Target with a reference to the generated and uploaded delta statistic file.
> Generate and upload delta stats

- lmp/jobserv.yml
Add lmp-mfgtool distro support for TI AM62XX-EVM board.
> lmp/jobserv: add mfgtool build for am62xx-evm

- lmp/bb-build.sh
It will be useful to get the buildstats results when OOM kill the bitbake and in any general errors.
> lmp/bb-build: add trap to do some pending operations on exit

- apps/target_apps_fetcher.py
Tiny changes to make the app preloader download and store all nodes/blobs of an app's Merkle tree.
It enables the new compose app management usage on devices for the early app start and offline updates use-cases since it requires presence of all app tree nodes so it can check its integrity.
> Fetch full app tree

- helpers.sh
These are the only repositories that require it. Furthermore, we've update source.fio/lmp-mirrors to redirect to github/lmp-mirrors. The git cloning fails because libcurl will see we have extra headers for source.fio and prompt for headers to send to github.
> helpers: Only send auth header for source.fio/factories

- helpers.py
oe-builtin logic is seeing a CI error like:
| Traceback (most recent call last):
|   File "/script-repo/preload_apps.py", line 14, in <module>
|     from apps.docker_registry_client import ThirdPartyRegistry
|   File "/script-repo/apps/docker_registry_client.py", line 18, in <module>
|     class DockerRegistryClient:
|   File "/script-repo/apps/docker_registry_client.py", line 19, in DockerRegistryClient
|     DefaultRegistryHost = 'hub.' + fio_dnsbase()
|   File "/script-repo/helpers.py", line 123, in fio_dnsbase
|     parts = urlparse(os.environ["H_RUN_URL"])
|   File "/usr/lib/python3.8/os.py", line 675, in __getitem__
|     raise KeyError(key) from None
| KeyError: 'H_RUN_URL'
This is because bitbake isolates the environment that it runs in. There are a couple ways to pass H_RUN_URL …
> helpers: Hack around MEDs/oe-builtin issue

- LICENSE
- apps/apps_publisher.py
- apps/build.sh
- apps/compose_apps.py
- apps/docker_registry_client.py
- apps/docker_to_compose.py
- apps/dockerd.py
- apps/fetch.py
- apps/image_downloader.py
- apps/publish.py
- apps/publish.sh
- apps/target_manager.py
- assemble-system-image.sh
- assemble.py
- factory-containers/publish-containers.sh
- lmp/customize-target.py
- lmp/customize-target.sh
- lmp/fetch-root-meta.sh
- lmp/fetch_root_meta.py
- preload-apps.sh
- preload_apps.py
- tag_manager.py
- tests/test_apps_fetch.sh
- tests/test_apps_publisher.py
- tests/test_apps_publishing.sh
- tests/test_compose_apps.py
- tests/test_container_build.sh
- tests/test_container_tagging.py
- tests/test_image_assembling.sh
Relicensing from Apache-v2 to BSD-3 Clause in order to align with other open source repositories owned by Foundries.io
> Relicense from Apache-v2 to BSD-3 Clause

- assemble.py
The return value was a generator of 2-value tuples not a dict
> assemble: Fix typing error

- assemble.py
If shortlist is not specified then a set containing target apps should be created to determine a set of the previously fetched app and the set of apps to fetch.
> assemble: Create set out of the target apps

- apps/fetch.py
- apps/target_apps_fetcher.py
- Convert the comma-separated list of apps represented as a string and provided as an input parameter to a list of string.
- Define the app shortlist as a list of strings in each function of the app fetcher.
> apps: Convert shortlist string to list

- lmp/jobserv.yml
The wayland distro was not been exercised and it is important that it is also.
> lmp/jobserv: add wayland distro flavor to main-next

- lmp/build-sdk-container.sh
- lmp/jobserv.yml
We had this logic in our old gitlab server and never migrated. The time has come.
> lmp: Build lmp-sdk container image

- apps/fetch.py
Don't set `shortlist` field in the custom.fetched-apps.shortlist field of a target if the `shortlist` attribute is not defined in `preloaded_images` nor `app_shortlist is defined in in `offline` sections of a factory config.
> apps: Add shortlist field to target only if set

- lmp/jobserv.yml
The scarthgap-next branch is to start exercising the scarthgap release on the ci.
> lmp/jobserv: add scarthgap-next

- apps/fetch.py
- apps/publish.sh
1. Add ability to disable apps update for offline update.
It adds the `fetched-apps.uri=None` value to each target, so the
target consumer, fioctl and aklite-offline, knows whether
to consider apps for the target offline update or not.
2. Don't set `fetched-apps.shortlist` field if shortlist is not specified or empty value.    
- Use target apps and shortlist intersection as the shortlist of apps to
fetch. Also, set the `fetched-apps.shortlist` value to this
intersection.
- Yield an error if no apps found to fetch for the given intersection of
target apps and the specified shortlist.
> Handle offline fetch apps edge cases

- apps/build.sh
- apps/fetch_app_images.py
Pull app images if the sbom generation is turned off.
If the sbom generation is turned ON, it pulls all app images to the local docker store. Then, the following script that gather information about app image layers parses the local docker store, therefore it assumes that all app images are present in the store.
If the sbom generation is OFF, then the 3rd party images are not present in the local store, hence they must be fetched to make the app layer metadata generation script work correctly. This is exactly what this change does.
> apps: Fetch app images if sbom is turned off

- lmp/bb-config.sh
We are introducing the ability for our partner factories to have sstate mirror objects in GCS. This change detects that based on the "forked-from" attribute we use a factory's factory-config.yml that will get set by our git server as a CI run parameter when triggering a build.
> lmp: Support partner mirrors

- helpers.sh
- lmp/bb-build.sh
When building public LmP **major release** we will generate the mirror tarball on the download folder of all git repos.
All the download files can be updated to the public download mirror at the end:
```
rsync -av --no-r --exclude=*.done --exclude=*.tmp /downloads/ /download-mirror/
```
> Generate mirror tarball

- lmp/build.sh
With this we can make this dir persistent which helps a lot in debugging with the simulator.
```
"persistent-volumes": {
"bitbake": "/var/cache/bitbake",
"oe": "/srv/oe"
},
```
To do that we need to inject this line on the `rundef.json` before launching the `jobserv_runner.simulator`:
```
cat <<< $(jq '."persistent-volumes"."oe"="/srv/oe"' rundef.json) > rundef.json
```
> lmp/build: add support to have a pre created /srv/oe dir

- helpers.sh
We are about to release a 94.1 version of the LmP. In the event of a 94.1 tag, we want to truncate the value and still use the "94" cache. This also allows the development of "95" to continue correctly.
The drawback to this approach is that the .1 part of the sstate cache is actually in the 95 bucket. 94.1 is small enough this doesn't matter. If we ever have a minor release that causes sufficient cache invalidation, then we'll need to re-think how to produce the cache better.
> helpers: Support minor releases of LmP in mirror code

- factory_client.py
Convert LmP version to float prior to converting it to int so minor LmP release versions are supported, e.g. "94.1".
> factory_client: Support LmP minor version conversion to int

- apps/publish.sh
Just tiny improvement that helps to identify an app publishing tool if the default one is override through setting the `PUBLISH_TOOL` env. variable.
> apps/publish: Print publish tool path if non-default

- lmp/bb-config.sh
Looks like bitbake is getting blocked just on the beginning when checking the sstate-mirror. 
Because we have custom log config we can't see the debug output on the default console and this change will make it possible.
> lmp/bb-config: temporarily disable our custom logconfig

- apps/build.sh
Makes the `dockerd-entrypoint.sh` script to run dockerd in the way it listens only the usual unix socket and avoiding listening on network ports `2375` or `2376`.
Also, it seems important to run the docked through `/usr/local/bin/dind`.
> apps/build.sh: Make dockerd listen only on unix socket

- apps/build.sh
It can be useful to see what machine architecture the `arch` detects inside of the CI container.
> apps/build.sh: Print detected arch in runner container

- lmp/bb-build.sh
- lmp/bb-config.sh
Add DISABLE_LOGCONFIG variable
When this was set to DISABLE_LOGCONFIG=1, the custom logconfig was disabled.
The custom logconfig when enabled, which is what we have by default, redirect the output to a file omitting it from appearing in the default build console.
> Control the bitbake logconfig

- lmp/build.sh
Simple lockdown script for UEFI Secure Boot.
> lmp/build.sh: deploy lockdown firmware

- lmp/bb-build.sh
This will run all pending do_rm_work task in the bitbake job instead of leaving it for the next job.
This way we don't see do_rm_work task on the next bitbake job that were left here by the previous one.
> lmp/bb-build: run the setscene-only job as much as possible

- apps/docker_store.py
- apps/get_layers_meta.py
Fix two issues detected while testing edge cases.
1. Layer digests should be set and used in a full format with the algorithm prefix.
2. Take into account that the docker daemon uses short form references for images hosted in docker.io during getting information about image layers.
> Fix digests of layers meta

- apps/target_apps_fetcher.py
It turned out that not enforcing the docker format for destination causes an issue if docker compose refers to an image manifest (usually compose refers to image index). For some reason `skopeo` don't copy/pull the original config blob referenced from an image manifest if the `--format` is not specified. It converts the original config blob and stores the converted blob...
> Revert "apps: Use source image format for destination"

- apps/build.sh
Set the `--variant` parameter value explicitly in the `docker manifest annotate` command, otherwise it may choose an incorrect variant type.
> apps: Set variant explicitly for arm and arm64

- lmp/jobserv.yml
- sync the machine list with stable job
- drop stm EULA
- move scarthgap-next to scarthgap
> lmp/jobserv: prepare the scarthgap job

- lmp/jobserv.yml
The deprecated machines were removed from the scarthgap and we will fix it in a followup.
> lmp/jobserv: temporarily drop from github_pr the deprecated machines

- lmp/jobserv.yml
This will use the same set of machines on two jobs:
build-release:
- track the lmp-manifest/main branch
build-scarthgap:
- track the lmp-manifest/scarthgap branch
> lmp/jobserv: alling the jobs build-release build-scarthgap

- lmp/bb-config.sh
This reverts commit ac2a7a510df38a59860618badbe73243957b56cb.
The repo is available again at Foundries.io github
- git://github.com/foundriesio/optee_os.git
> Revert "lmp/bb-config.sh: add custom repo for optee_os"

- lmp/build.sh
**- License handling**
Instead of blindly failing, this will improve the situation and will show up what is the missing manifests.
- Skip lmp-mfgtool disto variant ()
- Fail if the image manifest not exist
- Consider only the symbolic links of the images manifest
- From the licenses deploy dir of the image:
- Copy the license.manifest, if not possible fail
- Copy the image_license.manifest
_For the lmp-mfgtool we don't produce an image and don't make sense to processes the image manifest._
The following is an example of such blindly CI build fail:
```
| + for img in ${DEPLOY_DIR_IMAGE}/*${MACHINE}.manifest
| ++ basename '/srv/oe/build/deploy/images/intel-corei7-64/*intel-corei7-64.manifest'
| ++ sed -e s/.manifest//
| + image_name='*intel-corei7-64'
| ++ readlink …
```
> lmp/build: Improve license and source-code handling

- lmp/build-sdk-container.sh
- lmp/jobserv.yml
If the environment variable is present, use it as a tag when creating the container.
The default is build with the tag latest and also with the corresponding version tag.
> lmp/build-sdk-container: override the latest tag via an environment variable

- lmp/jobserv.yml
Fix Value 'LATEST=next' is not a dict.
> lmp/jobserv: build-sdk-container: fix LATEST params

- lmp/build-sdk-container.sh
Add the missing path argument.
> lmp/build-sdk-container: fixup docker build

- lmp/jobserv.yml
This is a temporary solution to get the main-next build on ci and generate the proper sstate-cache until the branch is ready for integration and merged on main.
> lmp/jobserv: add main-next ci job

- lmp/build-sdk-container.sh
- lmp/jobserv.yml
The move to 22.04 for the lmp-sdk container image requires us to be on a newer version of Docker to build that image. The new image:
* includes the change to unset DOCKER_HOST
* takes a little longer to start up
> lmp: Move to new docker-dind container

- lmp/build-sdk-container.sh
The current time is not enough as can be seen, so it is better to increase it to 60 seconds.
== 2025-05-27 21:12:51 Launching dockerd
== 2025-05-27 21:13:15 Timed out trying to connect to internal docker host
> lmp/build-sdk-container: incrase the dockerd launch timeout

- lmp/build-sdk-container.sh
The issue was in the DOCKER_HOST and so we can restore the previous timeout to 12 seconds.
> lmp/build-sdk-container: restore the timeout

- lmp/build-sdk-container.sh
This reverts commit 69fc5bf2e5747b7f822f9f7d54336e308ff67bef.
The current time is not enough so it is better to increase it again to 60 seconds.
> Revert "lmp/build-sdk-container: restore the timeout"

- lmp/jobserv.yml
The qemuarm64-secureboot is broken because of the fitimage so disable it until we get it working again.
> lmp/jobserv: main-next: drop qemuarm64-secureboot

- lmp/build.sh
Previously we exposed qcomflash tarballs, however, we also support zip archives for customers who interact with Windows a lot and are seeing corruption.  Let's expose those files as well.
> lmp/build: expose qcomflash zip archives

- lmp/jobserv.yml
Add raspberrypi5 to the pr machine list, as we now have the board available for wider testing.
> lmp: pr: add raspberrypi5
